db.Auth_user.insert({userId: "P900001234", pswd: "9ab93e37de8ea4f808e3a6cb02d5ec06"});

db.Counter.insert({seq: 0, col1: "VRNNum"});

db.LicenseRegion.insertMany([
	{Rg: "AN", Description: "Andaman & Nicobar"},
	{Rg: "AP", Description: "Andhra Pradesh"},
	{Rg: "ARP", Description: "Arunachal Pradesh"},
	{Rg: "AS", Description: "Assam"},
	{Rg: "BH", Description: "Bihar"},
	{Rg: "CD", Description: "Chandigarh"},
	{Rg: "CH", Description: "Chhatisgarh"},
	{Rg: "DDN", Description: "Daman & Diu"},
	{Rg: "DEL", Description: "Delhi"},
	{Rg: "DH", Description: "Dadra, Nagarhaveli"},
	{Rg: "GDD", Description: "Goa"},
	{Rg: "GJ", Description: "Gujarat"},
	{Rg: "HP", Description: "Himachal Pradesh"},
	{Rg: "HR", Description: "Haryana"},
	{Rg: "JH", Description: "Jharkhand"},
	{Rg: "JK", Description: "Jammu & Kashmir"},
	{Rg: "KAR", Description: "Karnataka"},
	{Rg: "KER", Description: "Kerala"},
	{Rg: "LAK", Description: "Lakshwadeep"},
	{Rg: "MAH", Description: "Maharashtra"},
	{Rg: "MEG", Description: "Meghalaya"},
	{Rg: "MP", Description: "Madhya Pradesh"},
	{Rg: "MR", Description: "Manipur"},
	{Rg: "MZ", Description: "Mizoram"},
	{Rg: "NG", Description: "Nagaland"},
	{Rg: "OR", Description: "Orissa"},
	{Rg: "PB", Description: "Punjab"},
	{Rg: "PY", Description: "Pondicherry"},
	{Rg: "RJ", Description: "Rajasthan"},
	{Rg: "SK", Description: "Sikkim"},
	{Rg: "TG", Description: "Telangana"},
	{Rg: "TN", Description: "Tamil Nadu"},
	{Rg: "TR", Description: "Tripura"},
	{Rg: "UC", Description: "Uttrakhand"},
	{Rg: "UP", Description: "Uttar Pradesh"},
	{Rg: "WB", Description: "West Bengal"}
]);

db.Params.insertMany([
{Domain: "TrnsprtMode", modeNum: "CA", modeTxt: "Courier Air", other1: ""},
{Domain: "TrnsprtMode", modeNum: "CR", modeTxt: "Courier Road", other1: ""},
{Domain: "TrnsprtMode", modeNum: "HD", modeTxt: "Hand Delivered", other1: ""},
{Domain: "TrnsprtMode", modeNum: "RB", modeTxt: "Road Bike", other1: ""},
{Domain: "TrnsprtMode", modeNum: "RD", modeTxt: "Road Truck", other1: ""},
{Domain: "FleetList", modeNum: "D", modeTxt: "Dedicated Vehicle", other1: "RD"},
{Domain: "FleetList", modeNum: "M", modeTxt: "Market Vehicle", other1: "RD"},
{Domain: "FleetList", modeNum: "V", modeTxt: "Vendor Vehicle", other1: "CA"},
{Domain: "FleetList", modeNum: "V", modeTxt: "Vendor Vehicle", other1: "CR"},
{Domain: "FleetList", modeNum: "B", modeTxt: "Biker", other1: "RB"},
{Domain: "IDProffList", modeNum: "AC", modeTxt: "Aadhar Card", other1: ""},
{Domain: "IDProffList", modeNum: "DL", modeTxt: "Driving License", other1: ""},
{Domain: "IDProffList", modeNum: "ED", modeTxt: "Employee ID", other1: ""},
{Domain: "IDProffList", modeNum: "OT", modeTxt: "Other", other1: ""},
{Domain: "IDProffList", modeNum: "PN", modeTxt: "PAN Number", other1: ""},
{Domain: "IDProffList", modeNum: "RC", modeTxt: "Ration Card", other1: ""},
{Domain: "IDProffList", modeNum: "VD", modeTxt: "Voter ID", other1: ""},
{Domain: "VEHICLESTATUS", modeNum: "L", modeTxt: "Loaded", other1: ""},
{Domain: "VEHICLESTATUS", modeNum: "E", modeTxt: "Empty", other1: " "},
{Domain: "SEALCONDITION", modeNum: "I", modeTxt: "Intact", other1: " "},
{Domain: "SEALCONDITION", modeNum: "D", modeTxt: "Damaged", other1: " "},
{Domain: "SEALCONDITION", modeNum: "N", modeTxt: "No Seal", other1: " "}
]);

db.Role_Plant.insert({userId: "P900001234", roleId: [ "VRN_OUT" ], plant: "1100", plantDesc: "MU-MUMB-JC-01"});

db.Transporter.insertMany([
{  
   Cl: 244,
   Vendor: "660090910",
   Cty: "IN",
   Name1: "DISTRIBUTOR TEST PARTNER",
   Name2: "",
   Name3: "",
   Name4: "QUENYN",
   City: "THANE",
   District: "THANE",
   POBox: "400701",
   POBoxpcd: "",
   PostalCode: 400701,
   Rg: "MAH",
   SearchTerm: "QUENYN",
   Street: "MG MARG",
   Address: 479415,
   Title: "Private Ltd",
   Date: "08-12-17",
   Createdby: "RFCUSER",
   ISRNumber: "",
   Group: "ZJIO",
   Customer: "",
   Telephone1: "+022-34569078",
   Telephone2: 919011123234,
   POBxcty: "12/A",
   Site: ""
},
{  
   Cl: 244,
   Vendor: "10000033",
   Cty: "IN",
   Name1: "TEST VENDOR",
   Name2: "",
   Name3: "",
   Name4: "QUENYN",
   City: "THANE",
   District: "THANE",
   POBox: "400701",
   POBoxpcd: "",
   PostalCode: 400701,
   Rg: "MAH",
   SearchTerm: "QUENYN",
   Street: "MG MARG",
   Address: 479417,
   Title: "Private Ltd",
   Date: "08-12-17",
   Createdby: "RFCUSER",
   ISRNumber: "",
   Group: "ZJIO",
   Customer: "",
   Telephone1: "+022-34569078",
   Telephone2: 919011123234,
   POBxcty: "12/A",
   Site: ""
},
{  
   Cl: 244,
   Vendor: "",
   Cty: "IN",
   Name1: "SAHIL",
   Name2: "",
   Name3: "",
   Name4: "QUENYN",
   City: "THANE",
   District: "THANE",
   POBox: "400701",
   POBoxpcd: "",
   PostalCode: 400701,
   Rg: "MAH",
   SearchTerm: "QUENYN",
   Street: "MG MARG",
   Address: 479419,
   Title: "Private Ltd",
   Date: "08-12-17",
   Createdby: "RFCUSER",
   ISRNumber: "",
   Group: "ZJIO",
   Customer: "",
   Telephone1: "+022-34569078",
   Telephone2: 919011123234,
   POBxcty: "12/A",
   Site: ""
}
]);